export {
  FRIENDLY_PLAYERS_ALLOWED,
  FRIENDLY_TEAMS_ALLOWED,
  assertGameOrganizer,
  assertMayCreateGameOnGroup,
  assertRegistrationOpen,
  assertUserPassesJoinGate,
  canViewGame,
  getRegistrationStatus,
  isClubGroupGameJoinFrozen,
  isGameOrganizer,
  isGroupMember,
  isRegistrationOpen,
  isStaffRole,
  mayCreateGameOnGroup,
  registeredGameTeamCount,
  registeredUserCount,
  registrationStatusFromState,
  requireGame,
  userPassesJoinGate,
  type GameRow,
  type RegistrationStatus,
} from "~/server/games/access";
export {
  admit,
  type AdmitDb,
  type AdmitDoor,
  type AdmitParty,
  type AdmitPlacement,
  type AdmitReason,
  type AdmitResult,
} from "~/server/games/admit";
export {
  listAssignableCourts,
  assertCourtAssignable,
  assertGameTeamOnGame,
} from "~/server/games/courts";
export {
  FRIENDLY_SET_SHELL_COUNT,
  backfillFriendlySetShells,
  createFriendlyGame,
  type CreateFriendlyDb,
  type CreateFriendlyGameInput,
  type CreateFriendlyGameResult,
} from "~/server/games/create-friendly";
export {
  listMyGamesHubRows,
  listPublicHubRows,
  toHubListRow,
  type HubListRow,
  type HubListSide,
  type HubListSideOccupant,
} from "~/server/games/hub-list-rows";
export {
  admitCompleteTeam,
  admitIndividualUser,
  assertGameInviteDoorsOpen,
  assertInviteeAllowedOnGame,
  eligibleCompleteTeamsForUser,
  recordTeamInviteLinkConsent,
} from "~/server/games/invites";
export {
  addTournamentMatch,
  cancelGame,
  cancelMatch,
  closeRegistration,
  kickRegisteredUser,
  kickWaitlistEntry,
  reopenRegistration,
  updateFriendlyGameMatchCourt,
  updateGameCaps,
  updateGameMatch,
  updateTournamentMatch,
  updateGamePricePerPlayer,
  updateGameWindow,
  type MatchUpdateInput,
  type TournamentMatchInput,
} from "~/server/games/organize";
export {
  assertFullyVacantSide,
  firstFullyVacantSideIndex,
  firstVacantPosition,
  highestOccupiedSideIndex,
  insertIndividualPairOnVacantSide,
  isIndividualSeatGame,
  listGameSides,
  moveToSeat,
  occupySeat,
  otherPosition,
  remainingCapacity,
  setFriendlyMatchSlotForSide,
  sideCount,
  sitsOnCompletedMatch,
  vacateSeat,
  vacantPositionsFromSides,
  type GameSide,
  type SeatOccupant,
  type SeatPosition,
  type VacatedSeat,
} from "~/server/games/seats";
export {
  addMatchSet,
  assertMayWriteSets,
  bothSlotsFilled,
  bothSlottedTeamsComplete,
  completeMatch,
  matchOutcome,
  removeMatchSet,
  requireMatchOnGame,
  scoreMatchSet,
  setWinsForGames,
  userIsOnMatchSlots,
} from "~/server/games/sets";
export {
  loadGameCreateVenueContext,
  listVenuesForGameCreate,
  assertGameCreateVenueAndCourt,
  type GameCreateGroupKind,
  type GameCreateVenueContext,
  type GameCreateVenueOption,
} from "~/server/games/venue";
export {
  clearMatchSlotsForGameTeam,
  enqueueWaitlistTeam,
  enqueueWaitlistUser,
  leaveRegisteredSeat,
  leaveWaitlistEntry,
  promoteWaitlist,
  removeGameTeamAndPlayers,
} from "~/server/games/waitlist";
